import Head from "next/head";
import React, { FC, PropsWithChildren } from "react";
import { IMenu } from "../../app/models/menu.interface";
import Navbar from "../UI/Navbar";
import styles from "./Layout.module.scss";
interface Props {
  title?: string;
  menus: IMenu[];
}

const Layout: FC<PropsWithChildren<Props>> = ({
  children,
  title = "tashbus",
  menus,
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar menus={menus} />
        {children}
      </main>
    </>
  );
};

export default Layout;
